"""Compatibility exports for the practice repository domain."""

from . import _legacy

from ._legacy import (
    PHASE9C_SESSION_TITLE_MAX,
    PHASE9C_SESSION_MAX_ITEMS,
    PHASE9C_MIN_DURATION_SECONDS,
    PHASE9C_MAX_DURATION_SECONDS,
    PHASE9C_FEEDBACK_MAX,
    PHASE9C_CORRECTION_MAX,
    PHASE9C_SESSION_STATUSES,
    PHASE9C_MISTAKE_STATUSES,
    PHASE9C_SOURCE_STATUSES,
    create_cram_goal,
    get_cram_goal,
    list_cram_goals,
    transition_cram_goal,
    create_cram_session,
    get_cram_result,
    create_practice_session,
    get_practice_session,
    list_practice_sessions,
    get_practice_result,
    start_practice_session,
    archive_practice_session,
    submit_practice_session_item,
    finish_practice_session,
    mark_mistake_from_attempt,
    review_exercise_attempt,
    add_mistake_feedback,
    archive_mistake_case,
    get_mistake_case,
    list_mistake_cases,
    redo_mistake_case,
    list_weak_points,
)

__all__ = [
    'PHASE9C_SESSION_TITLE_MAX',
    'PHASE9C_SESSION_MAX_ITEMS',
    'PHASE9C_MIN_DURATION_SECONDS',
    'PHASE9C_MAX_DURATION_SECONDS',
    'PHASE9C_FEEDBACK_MAX',
    'PHASE9C_CORRECTION_MAX',
    'PHASE9C_SESSION_STATUSES',
    'PHASE9C_MISTAKE_STATUSES',
    'PHASE9C_SOURCE_STATUSES',
    'create_cram_goal',
    'get_cram_goal',
    'list_cram_goals',
    'transition_cram_goal',
    'create_cram_session',
    'get_cram_result',
    'create_practice_session',
    'get_practice_session',
    'list_practice_sessions',
    'get_practice_result',
    'start_practice_session',
    'archive_practice_session',
    'submit_practice_session_item',
    'finish_practice_session',
    'mark_mistake_from_attempt',
    'review_exercise_attempt',
    'add_mistake_feedback',
    'archive_mistake_case',
    'get_mistake_case',
    'list_mistake_cases',
    'redo_mistake_case',
    'list_weak_points',
]
