const {test,expect}=require('@playwright/test');const{spawn}=require('child_process');const fs=require('fs');
const ROOT='H:/studybuddy-test/runs/practice-recommendations';const PORT=8834;const BASE=`http://127.0.0.1:${PORT}`;let server;
function start(){const env={...process.env,PYTHONPATH:'H:/studybuddy/backend',STUDYBUDDY_DATA_ROOT:ROOT,STUDYBUDDY_AI_PROVIDER:'fake'};return spawn('C:/miniconda/py310/python.exe',['-m','uvicorn','app.main:app','--host','127.0.0.1','--port',String(PORT)],{cwd:'H:/studybuddy/backend',env,stdio:'ignore',windowsHide:true})}
async function ready(){await expect.poll(async()=>{try{return(await fetch(`${BASE}/api/readiness`)).ok}catch(_){return false}},{timeout:15000}).toBe(true)}
async function stop(){if(!server||server.killed){server=null;return}await new Promise(resolve=>{const finish=()=>resolve();server.once('exit',finish);server.kill();setTimeout(finish,5000)});server=null}
test.beforeEach(async()=>{fs.rmSync(ROOT,{recursive:true,force:true});server=start();await ready()});test.afterEach(async()=>{await stop()});
async function mock(page,url,body,status=200){await page.route(url,route=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)}))}
test('practice recommendations load, select and create session without starting it',async({page})=>{let created=null;const items=[{exercise_id:'exercise-1',exercise_type:'true_false',prompt:'公开推荐题',options:[],status:'ready',source_status:'valid',reason_codes:['never_attempted','source_valid'],reason_labels:['尚未练习','来源当前可用'],attempt_summary:{attempt_count:0,incorrect_count:0,pending_review_count:0,last_attempt_at:null}}];await mock(page,'**/api/study/practice-recommendations*',{status:'ready',items});await page.route('**/api/study/practice-sessions',async route=>{if(route.request().method()==='POST'){created=JSON.parse(route.request().postData());await route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({id:'session-new',status:'draft'})})}else await route.fulfill({status:200,contentType:'application/json',body:'[]'})});await page.goto(`${BASE}/app/practice.html`);await expect(page.locator('#recommendations')).toContainText('公开推荐题');await expect(page.locator('#recommendations')).toContainText('尚未练习');await page.locator('#recommendations input').check();await page.getByRole('button',{name:'创建练习会话'}).click();await expect(page).toHaveURL(/practice-session\.html\?session_id=session-new/);expect(created.exercise_ids).toEqual(['exercise-1']);expect(created).not.toHaveProperty('start')});
test('recommendations show empty and safe retry after failure',async({page})=>{let reads=0;await page.route('**/api/study/practice-recommendations*',route=>{reads++;return route.fulfill({status:reads===1?500:200,contentType:'application/json',body:JSON.stringify(reads===1?{detail:'private_backend_error',traceback:'hidden'}:{status:'empty',items:[]})})});await page.goto(`${BASE}/app/practice.html`);await expect(page.locator('#recommendation-status')).toContainText('请求失败');await page.getByRole('button',{name:'刷新推荐'}).click();await expect(page.locator('#recommendation-status')).toContainText('暂无可用推荐题目');expect(reads).toBe(2);await expect(page.locator('body')).not.toContainText(/private_backend_error|traceback|answer_key|answer_json/i)});
test('recommendations remain usable on 390px keyboard path',async({page})=>{const items=[{exercise_id:'exercise-key',exercise_type:'true_false',prompt:'键盘推荐题',options:[],status:'ready',source_status:'valid',reason_codes:['never_attempted'],reason_labels:['尚未练习'],attempt_summary:{attempt_count:0,incorrect_count:0,pending_review_count:0,last_attempt_at:null}}];await mock(page,'**/api/study/practice-recommendations*',{status:'ready',items});await page.route('**/api/study/practice-sessions',async route=>{if(route.request().method()==='POST')await route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({id:'keyboard-session',status:'draft'})});else await route.fulfill({status:200,contentType:'application/json',body:'[]'})});await page.setViewportSize({width:390,height:844});await page.goto(`${BASE}/app/practice.html`);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);const checkbox=page.locator('#recommendations input');await checkbox.focus();await page.keyboard.press('Space');await expect(page.getByRole('button',{name:'创建练习会话'})).toBeEnabled();await page.getByRole('button',{name:'创建练习会话'}).focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(/practice-session\.html\?session_id=keyboard-session/);await expect(page.locator('body')).not.toContainText(/answer_key|answer_json|grading payload|traceback/i)});
