const {test, expect} = require('@playwright/test');
const {spawn} = require('child_process');
const fs = require('fs');
const ROOT = 'H:/studybuddy-test/runs/p2-fe3-qa-app';
const PORT = 8793;
const BASE = `http://127.0.0.1:${PORT}`;
function start(provider = 'fake') { const env = {...process.env, PYTHONPATH: 'H:/studybuddy/backend', STUDYBUDDY_DATA_ROOT: ROOT, STUDYBUDDY_AI_PROVIDER: provider}; return spawn('C:/miniconda/py310/python.exe', ['-m','uvicorn','app.main:app','--host','127.0.0.1','--port',String(PORT)], {cwd:'H:/studybuddy/backend',env,stdio:'ignore',windowsHide:true}); }
async function ready() { for(let i=0;i<100;i++){try{if((await fetch(`${BASE}/api/health`)).ok)return}catch(_){ } await new Promise(r=>setTimeout(r,100))} throw new Error('server_not_ready') }
function stop(server){if(server&&!server.killed)server.kill()}
async function createMaterial(page,name,body){const response=await page.request.post(`${BASE}/api/materials`,{multipart:{file:{name,mimeType:'text/plain',buffer:Buffer.from(body)}}});expect(response.ok()).toBeTruthy();const data=await response.json();return String(data.id||data.material_id)}
async function index(page,id){const response=await page.request.post(`${BASE}/api/materials/${id}/ai-index`);expect(response.ok()).toBeTruthy()}

test.beforeEach(async()=>{fs.rmSync(ROOT,{recursive:true,force:true})});

test('formal app QA selects real materials, requires index, answers and follows citation', async({page})=>{const server=start();try{await ready();const id=await createMaterial(page,'qa-alpha.txt','P1 citation evidence identifies the indexed body location. This verified study source contains enough public text for lexical retrieval. The indexed body location is supported by the citation evidence in this material.');await page.goto(`${BASE}/app/qa.html`);await expect(page.locator('#material-picker .material-choice')).toHaveCount(1);await page.locator('#material-picker input').check();await expect(page.locator('#materials')).toHaveValue(id);await page.locator('#question').fill('citation evidence indexed body location');await page.locator('#retrieval-mode').selectOption('lexical');await page.locator('#submit-btn').click();await expect(page.locator('#submit-status')).toContainText('材料索引尚未建立');await index(page,id);await page.locator('#index-btn').click();await expect(page.locator('#submit-status')).toContainText('索引建立完成');await page.locator('#submit-btn').click();await expect(page.locator('#submit-status')).toContainText('回答已生成',{timeout:15000});const openButtons=page.getByRole('button',{name:'查看对话与引用'});const openCount=await openButtons.count();for(let i=0;i<openCount;i++){await openButtons.nth(i).click()}const citation=page.locator('.thread-detail .citation-link');await expect(citation).toHaveCount(1);await citation.click();await expect(page).toHaveURL(/material-detail\.html\?material=.*&citation=/);await expect(page.locator('#body mark.citation-highlight')).toContainText('P1 citation evidence');}finally{stop(server)}});

test('formal app QA keeps selected scope, safely retries ask failure and blocks duplicate submit', async({page})=>{const server=start();try{await ready();const id=await createMaterial(page,'qa-retry.txt','Retry citation evidence establishes a stable answer.');await index(page,id);await page.goto(`${BASE}/app/qa.html?material=${id}`);await expect(page.locator('#material-picker input')).toBeChecked();await page.locator('#question').fill('stable answer');await page.locator('#retrieval-mode').selectOption('lexical');let calls=0;let fail=true;await page.route(`${BASE}/api/qa/ask`,async route=>{calls++;if(fail)return route.fulfill({status:504,contentType:'application/json',body:JSON.stringify({detail:'provider_timeout',path:'H:/private',traceback:'hidden'})});return route.continue()});await page.locator('#submit-btn').click();await expect(page.locator('#submit-status')).toContainText('Provider 请求超时');await expect(page.locator('#question')).toHaveValue('stable answer');await expect(page.locator('body')).not.toContainText(/provider_timeout|H:\/private|hidden/);fail=false;await page.unroute(`${BASE}/api/qa/ask`);await page.locator('#submit-btn').click();await expect(page.locator('#submit-status')).toContainText('回答已生成',{timeout:15000});expect(calls).toBe(1);let duplicate=0;await page.route(`${BASE}/api/qa/ask`,async route=>{duplicate++;await new Promise(r=>setTimeout(r,300));return route.continue()});await page.locator('#question').fill('stable answer');await page.locator('#submit-btn').click();await expect(page.locator('#submit-btn')).toBeDisabled();await page.locator('#submit-btn').click({force:true});await expect(page.locator('#submit-status')).toContainText('回答已生成',{timeout:15000});expect(duplicate).toBe(1)}finally{stop(server)}});

test('formal app QA supports multiple selected materials, history failure and narrow layout', async({page})=>{const server=start();try{await ready();const one=await createMaterial(page,'qa-one.txt','First material contains the first citation.');const two=await createMaterial(page,'qa-two.txt','Second material contains the second citation.');await index(page,one);await index(page,two);await page.goto(`${BASE}/app/qa.html`);await page.locator('#material-picker input').nth(0).check();await page.locator('#material-picker input').nth(1).check();await expect(page.locator('#materials')).toHaveValue(new RegExp(`${one}.*${two}|${two}.*${one}`));await page.locator('#question').fill('contains the citation');await page.locator('#retrieval-mode').selectOption('lexical');await page.locator('#submit-btn').click();await expect(page.locator('#submit-status')).toContainText('回答已生成',{timeout:15000});await page.getByRole('button',{name:'查看对话与引用'}).click();await expect(page.locator('.thread-detail .citation-link')).toHaveCount(2);await page.route(`${BASE}/api/qa/threads`,route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'private'})}));await page.reload();await expect(page.locator('#thread-status')).toContainText('请求失败，请重试');await expect(page.locator('body')).not.toContainText('private');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy()}finally{stop(server)}});

test('formal app QA safely reports unconfigured provider', async({page})=>{const server=start('');try{await ready();await page.goto(`${BASE}/app/qa.html`);await expect(page.locator('#provider-status')).toContainText('AI Provider 未配置');await expect(page.locator('body')).not.toContainText(/traceback|api_key|H:\\private/)}finally{stop(server)}});
