const { test, expect } = require('@playwright/test');
const { spawn } = require('child_process');
const path = require('path');
const fixture = path.resolve('H:/studybuddy-test/fixtures/kaobuddy-foundation/sample.txt');
const folderFixture = path.resolve('H:/studybuddy-test/fixtures/kaobuddy-foundation');
const BASE = 'http://127.0.0.1:8791';
let server;
test.beforeEach(async () => { server = spawn('D:/miniconda/py310/python.exe', ['-m', 'uvicorn', 'app.main:app', '--host', '127.0.0.1', '--port', '8791'], { cwd: 'H:/studybuddy/backend', env: {...process.env, PYTHONPATH: 'H:/studybuddy/backend', STUDYBUDDY_DATA_ROOT: 'H:/studybuddy-test/runs/formal-frontend-failure-contract'}, stdio: 'ignore', windowsHide: true }); await expect.poll(async () => { try { return (await fetch(`${BASE}/api/health`)).ok; } catch (_) { return false; } }, { timeout: 15000 }).toBe(true); });
test.afterEach(() => { if (server && !server.killed) server.kill(); server = null; });
const forbidden = ['stored_path', 'traceback', 'database is locked', 'C:/secret', 'internal backend text'];
async function assertSafe(page){const text=(await page.locator('body').innerText()).toLowerCase();for(const value of forbidden)expect(text).not.toContain(value.toLowerCase())}
async function load(page){await page.goto(BASE);await expect(page.locator('#status')).toBeVisible()}

test('single import failure restores controls and followup succeeds',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e));let fail=true;await page.route('**/api/materials',async route=>fail?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'material_persist_failed',path:'C:/secret',trace:'fake'})}):route.continue());await load(page);await page.locator('#file').setInputFiles(fixture);await page.locator('#file-import').click();await expect(page.locator('#status')).toHaveText('导入失败');await expect(page.locator('#file-import')).toBeEnabled();await assertSafe(page);fail=false;await page.locator('#file').setInputFiles(fixture);await page.locator('#file-import').click();await expect(page.locator('#status')).toContainText('导入完成');expect(errors).toHaveLength(0)})

test('folder failure is generic and controls restore',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e));await page.route('**/api/materials/batch',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'folder secret',stored_path:'C:/secret',traceback:'fake'})}));await load(page);await page.locator('#folder').setInputFiles(folderFixture);await page.locator('#folder-import').click();await expect(page.locator('#status')).toHaveText('文件夹导入失败');await expect(page.locator('#folder-import')).toBeEnabled();await assertSafe(page);expect(errors).toHaveLength(0)})

test('batch partial and malformed payload are safe',async({page})=>{let malformed=false;await page.route('**/api/materials/batch',route=>route.fulfill({status:201,contentType:'application/json',body:malformed?JSON.stringify({items:'bad'}):JSON.stringify({batch_id:'synthetic',total:3,success:1,empty:0,rejected:1,failed:1,items:[{original_name:'ok.txt',status:'success',material_id:null,warnings:[]},{original_name:'bad.txt',status:'rejected',error_code:'file_too_large',warnings:[]},{original_name:'failed.txt',status:'failed',error_code:'material_persist_failed',warnings:[]}]})}));await load(page);await page.locator('#file').setInputFiles([fixture,fixture]);await page.locator('#file-import').click();await expect(page.locator('#summary')).toContainText('总数 3');await expect(page.locator('#file-import')).toBeEnabled();await assertSafe(page);malformed=true;await page.locator('#file').setInputFiles([fixture,fixture]);await page.locator('#file-import').click();await expect(page.locator('#status')).toHaveText('导入失败');await expect(page.locator('#file-import')).toBeEnabled();await assertSafe(page)})

test('network rejection restores import controls',async({page})=>{await page.route('**/api/materials',route=>route.abort());await load(page);await page.locator('#file').setInputFiles(fixture);await page.locator('#file-import').click();await expect(page.locator('#status')).toHaveText('导入失败');await expect(page.locator('#file-import')).toBeEnabled();await assertSafe(page)})
