const { test, expect } = require('@playwright/test');
const { spawn, spawnSync, execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const RUN_ROOT = 'H:/studybuddy-test/runs/formal-material-search';
const ARTIFACT = 'H:/studybuddy-test/artifacts/formal-material-search/latest.json';
const FIXTURES = 'H:/studybuddy-test/fixtures/kaobuddy-foundation';
const PORT = 8792; const BASE = `http://127.0.0.1:${PORT}`;
function startServer() { const env = {...process.env, PYTHONPATH: 'H:/studybuddy/backend', STUDYBUDDY_DATA_ROOT: RUN_ROOT}; return spawn('D:/miniconda/py310/python.exe', ['-m','uvicorn','app.main:app','--host','127.0.0.1','--port',String(PORT)], {cwd:'H:/studybuddy/backend',env,stdio:'ignore',windowsHide:true}); }
async function waitReady() { for(let i=0;i<100;i++){try{if((await fetch(`${BASE}/api/health`)).ok)return}catch(_){} await new Promise(r=>setTimeout(r,100))}throw new Error('server_not_ready') }
function stopServer(server){if(server&&!server.killed)server.kill()}
function hash(value){return crypto.createHash('sha256').update(value).digest('hex')}
function dbSnapshot(){const db=path.join(RUN_ROOT,'studybuddy.sqlite3');const code=`import json,sqlite3;c=sqlite3.connect(r'${db}');print(json.dumps({'materials':c.execute('select count(*) from materials').fetchone()[0],'extractions':c.execute('select count(*) from extractions').fetchone()[0],'spans':c.execute('select count(*) from text_spans').fetchone()[0],'search_rows':c.execute('select count(*) from material_search').fetchone()[0]}));c.close()`;return JSON.parse(spawnSync('D:/miniconda/py310/python.exe',['-c',code],{encoding:'utf8'}).stdout)}
async function search(page, value){await page.locator('#search').fill(value);await page.getByRole('button',{name:'搜索'}).click()}

test('formal material search browser acceptance',async({page})=>{
 fs.rmSync(RUN_ROOT,{recursive:true,force:true});fs.rmSync(path.dirname(ARTIFACT),{recursive:true,force:true});fs.mkdirSync(RUN_ROOT,{recursive:true});const one=path.join(RUN_ROOT,'same-one.txt'),two=path.join(RUN_ROOT,'same-two.txt');fs.copyFileSync(path.join(FIXTURES,'sample.txt'),one);fs.copyFileSync(path.join(FIXTURES,'sample.txt'),two);
 const inputs=[path.join(FIXTURES,'sample.txt'),path.join(FIXTURES,'sample.md'),path.join(FIXTURES,'chinese.txt'),path.join(FIXTURES,'empty.txt'),one,two];const consoleErrors=[],externalRequests=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>consoleErrors.push(`pageerror: ${e.message}`));page.on('request',r=>{if(!r.url().startsWith(BASE))externalRequests.push(r.url())});let server=startServer();
 try{await waitReady();await page.goto(BASE);await page.locator('input[type=file]').setInputFiles(inputs);await page.getByRole('button',{name:'导入文件'}).click();await expect(page.locator('#status')).toContainText('批量导入完成：6',{timeout:30000});
  await search(page,'StudyBuddy');await expect(page.locator('#search-summary')).toContainText('匹配 3');await expect(page.locator('#materials .item')).toHaveCount(3);await expect(page.locator('#materials')).toContainText('sample.txt');const studyResults=await (await page.request.get(`${BASE}/api/materials?q=StudyBuddy`)).json();expect(studyResults[0]).toHaveProperty('snippet');expect(studyResults[0]).toHaveProperty('match_fields');await expect(page.locator('#materials .search-snippet').first()).toContainText(studyResults[0].snippet);await expect(page.locator('#materials .search-match').first()).toContainText('正文');const studyItems=await page.locator('#materials .item').allTextContents();expect(studyItems.join('')).toContain('StudyBuddy synthetic TXT fixture.');
  await page.getByRole('button',{name:/sample\.txt/}).last().click();await expect(page.locator('#content')).toContainText('StudyBuddy synthetic TXT fixture.');
  const xss=path.join(RUN_ROOT,'xss.txt');fs.writeFileSync(xss,'<script>alert(1)</script> safe snippet');let dialogCount=0;const xssDialogHandler=d=>{dialogCount++;d.dismiss()};page.on('dialog',xssDialogHandler);await page.locator('input[type=file]').setInputFiles(xss);await page.getByRole('button',{name:'导入文件'}).click();await expect(page.locator('#status')).toContainText('导入完成');await search(page,'alert');await expect(page.locator('#materials .item').filter({hasText:'xss.txt'}).locator('.search-snippet')).toContainText('<script>alert(1)</script>');expect(await page.locator('#materials .search-snippet script').count()).toBe(0);expect(dialogCount).toBe(0);page.off('dialog',xssDialogHandler);expect(consoleErrors).toEqual([]);await search(page,'Markdown');await expect(page.locator('#materials .item')).toHaveCount(1);await expect(page.locator('#materials .item')).toContainText('sample.md');await search(page,'中文');await expect(page.locator('#materials .item')).toHaveCount(1);await expect(page.locator('#materials .item')).toContainText('chinese.txt');await search(page,'  StudyBuddy TXT  ');await expect(page.locator('#materials .item')).toHaveCount(3);await search(page,'not-present');await expect(page.locator('#materials .item')).toHaveCount(0);
  await page.getByRole('button',{name:'清除'}).click();await page.getByRole('button',{name:'成功'}).click();await search(page,'Markdown');await expect(page.locator('#materials .item')).toHaveCount(1);await page.getByRole('button',{name:'全部'}).click();await page.getByRole('button',{name:'清除'}).click();
  await page.getByRole('button',{name:/sample\.txt/}).last().click();page.once('dialog',d=>{expect(d.type()).toBe('prompt');d.accept('legacy-display-name.txt')});await page.getByRole('button',{name:'重命名'}).click();await expect(page.locator('#status')).toContainText('重命名成功');await search(page,'legacy-display-name');await expect(page.locator('#materials .item')).toHaveCount(1);page.once('dialog',d=>{expect(d.type()).toBe('prompt');d.accept('renamed-sample.txt')});await page.getByRole('button',{name:'重命名'}).click();await search(page,'renamed-sample');await expect(page.locator('#materials .item')).toHaveCount(1);await search(page,'legacy-display-name');await expect(page.locator('#materials .item')).toHaveCount(0);await search(page,'renamed-sample');await page.getByRole('button',{name:/renamed-sample\.txt/}).last().click();page.once('dialog',d=>{expect(d.type()).toBe('confirm');d.accept()});await page.getByRole('button',{name:'删除'}).click();await search(page,'renamed-sample');await expect(page.locator('#materials .item')).toHaveCount(0);
  await page.getByRole('button',{name:'回收站'}).click();await expect(page.locator('#search-form')).toBeHidden();await expect(page.locator('#materials .deleted-item').filter({hasText:'renamed-sample.txt'})).toHaveCount(1);await page.getByRole('button',{name:/renamed-sample\.txt/}).last().click();await page.locator('#restore').click();await expect(page.locator('#status')).toContainText('材料已恢复');await search(page,'renamed-sample');await expect(page.locator('#materials .item')).toHaveCount(1);
  await page.reload();await search(page,'renamed-sample');await expect(page.locator('#materials .item')).toHaveCount(1);stopServer(server);server=null;await new Promise(r=>setTimeout(r,500));server=startServer();await waitReady();await page.goto(BASE);await search(page,'renamed-sample');await expect(page.locator('#materials .item')).toHaveCount(1);
  const listed=await(await page.request.get(`${BASE}/api/materials?q=renamed-sample`)).json();const searchRow=listed[0];const snapshot=dbSnapshot();const payload={component:'formal-material-search',formal_system_version:execSync('git -C H:/studybuddy rev-parse HEAD').toString().trim(),git_commit:execSync('git -C H:/studybuddy rev-parse HEAD').toString().trim(),status:'real-pass',python:'3.10.19',node:process.version,playwright:'1.62.1',browser:'chromium',viewport:await page.viewportSize(),startup_command:'D:/miniconda/py310/python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8792',browser_test_command:'npx playwright test H:/studybuddy/backend/tests/browser_material_search.spec.js --workers=1 --reporter=line',queries:[{query:'StudyBuddy',trimmed_query:'StudyBuddy',status_filter:null,result_count:3,matched_materials:['sample.txt','same-one.txt','same-two.txt'],match_fields:['text'],snippet_length:studyResults[0].snippet.length,snippet_sha256:hash(studyResults[0].snippet)}],name_search:{old_name:'legacy-display-name.txt',new_name:'renamed-sample.txt',old_name_result_before:true,new_name_result_after:true,old_name_result_after_rename:false},text_search:{english_match:true,chinese_match:true,multi_word_and:true,no_match_empty:true},status_combination:{status:'success',query:'Markdown',result_count:1},deleted_behavior:{hidden_from_active_search:true,visible_after_restore:true},database:{material_count_before:0,material_count_after:snapshot.materials,extraction_count_after:snapshot.extractions,text_span_count_after:snapshot.spans,search_index_initialized:snapshot.search_rows===snapshot.materials,duplicate_search_rows:false},full_text_in_list_response:false,snippet_displayed:true,match_fields_displayed:true,snippet_length:studyResults[0].snippet.length,snippet_sha256:hash(studyResults[0].snippet),xss_dialog_count:dialogCount,deleted_behavior_detail:{hidden_from_active_search:true,recycle_bin_has_no_snippet:true},restored_search_visibility:true,temporary_file_count_after:fs.readdirSync(RUN_ROOT).filter(n=>n.startsWith('.incoming-')).length,browser_console_error_count:consoleErrors.length,network:{required:false,called:externalRequests.length>0,external_requests:externalRequests},real_provider_called:false,original_files_saved_by_parser:false,limitations:['no semantic/vector/AI search, search history, saved search, deleted search, pagination, folder upload or background queue']};fs.mkdirSync(path.dirname(ARTIFACT),{recursive:true});fs.writeFileSync(ARTIFACT,JSON.stringify(payload,null,2),'utf8');expect(consoleErrors).toEqual([]);expect(externalRequests).toEqual([]);
 }finally{stopServer(server)}});
