const {test,expect}=require('@playwright/test');const {spawn}=require('child_process');const fs=require('fs');
const ROOT='H:/studybuddy-test/runs/p1-4-c4-5-browser',PORT=8867,BASE=`http://127.0.0.1:${PORT}`;let server;
function start(){return spawn('C:/miniconda/py310/python.exe',['-m','uvicorn','app.main:app','--host','127.0.0.1','--port',String(PORT)],{cwd:'H:/studybuddy/backend',env:{...process.env,PYTHONPATH:'H:/studybuddy/backend',STUDYBUDDY_DATA_ROOT:ROOT,STUDYBUDDY_AI_PROVIDER:'fake'},stdio:'ignore',windowsHide:true})}
async function ready(){await expect.poll(async()=>{try{return(await fetch(BASE+'/api/health')).ok}catch(_){return false}},{timeout:20000}).toBe(true)}async function stop(){if(!server||server.killed)return;await new Promise(r=>{server.once('exit',r);server.kill();setTimeout(r,5000)});server=null}
async function upload(request,index){const response=await request.post(BASE+'/api/materials',{multipart:{file:{name:`measure-${index}.txt`,mimeType:'text/plain',buffer:Buffer.from(`bounded browser measurement material ${index}`)}}});expect(response.status()).toBe(201)}
test.beforeEach(async()=>{await stop();fs.rmSync(ROOT,{recursive:true,force:true});server=start();await ready()});test.afterEach(stop);
test('measure app materials rendering and task controls without product thresholds',async({page,request})=>{
 for(let i=0;i<20;i++)await upload(request,i);const start=Date.now();await page.goto(BASE+'/app/materials.html');await expect(page.locator('#items li')).toHaveCount(20);console.log(`C4-5 materials app render 20 rows: ${Date.now()-start} ms`);
 const indexed=await request.post(BASE+'/api/materials/measure-absent/ai-index');expect(indexed.status()).toBe(404);
 const material=await (await request.get(BASE+'/api/materials?limit=1')).json();const id=material.items[0].id;const indexResponse=await request.post(`${BASE}/api/materials/${id}/ai-index`);expect(indexResponse.ok()).toBeTruthy();const taskResponse=await request.post(`${BASE}/api/materials/${id}/ai-index/tasks`,{headers:{'Idempotency-Key':'c4-5-control'}});expect(taskResponse.status()).toBe(202);const task=await taskResponse.json();
 const taskStart=Date.now();await page.goto(BASE+'/app/tasks.html');await expect(page.locator('#tasks')).toContainText('embedding_index');console.log(`C4-5 tasks app render: ${Date.now()-taskStart} ms`);
 await page.route('**/api/tasks?*',r=>r.fulfill({status:500,contentType:'application/json',body:'{"detail":"private_failure"}'}));await page.getByRole('button',{name:'刷新'}).click();await expect(page.locator('#error')).toContainText('请求失败');expect(await page.locator('#error').textContent()).not.toContain('private_failure');await page.unrouteAll({behavior:'ignoreErrors'});
 await page.goto(`${BASE}/app/tasks.html?task_id=${task.task_id}`);await expect(page.locator('#task-detail')).toBeVisible();const cancel=page.getByRole('button',{name:'取消'});if(await cancel.count()){const controlStart=Date.now();await page.once('dialog',d=>d.accept());await cancel.click();await expect(page.locator('#task-detail')).toContainText('已取消');console.log(`C4-5 controls: cancel queued task ${task.task_id} ${Date.now()-controlStart} ms`)}else{console.log(`C4-5 controls: task ${task.task_id} completed before cancel observation`)}
});
