const { test, expect } = require('@playwright/test');
const { spawn, spawnSync, execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const RUN_ROOT = 'H:/studybuddy-test/runs/formal-material-export';
const ARTIFACT = 'H:/studybuddy-test/artifacts/formal-material-export/latest.json';
const FIXTURES = 'H:/studybuddy-test/fixtures/kaobuddy-foundation';
const PORT = 8791;
const BASE = `http://127.0.0.1:${PORT}`;
function startServer() { const env = {...process.env, PYTHONPATH: 'H:/studybuddy/backend', STUDYBUDDY_DATA_ROOT: RUN_ROOT}; return spawn('D:/miniconda/py310/python.exe', ['-m', 'uvicorn', 'app.main:app', '--host', '127.0.0.1', '--port', String(PORT)], {cwd: 'H:/studybuddy/backend', env, stdio: 'ignore', windowsHide: true}); }
async function waitReady() { for (let i = 0; i < 100; i++) { try { if ((await fetch(`${BASE}/api/health`)).ok) return; } catch (_) {} await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('server_not_ready'); }
function stopServer(server) { if (server && !server.killed) server.kill(); }
function hashBuffer(buffer) { return crypto.createHash('sha256').update(buffer).digest('hex'); }
function originalCount() { const root = path.join(RUN_ROOT, 'originals'); return fs.existsSync(root) ? fs.readdirSync(root, {recursive: true}).filter(name => path.basename(name) === 'original').length : 0; }
function dbCounts() { const db = path.join(RUN_ROOT, 'studybuddy.sqlite3'); const code = `import json,sqlite3;c=sqlite3.connect(r'${db}');print(json.dumps({"materials":c.execute('SELECT COUNT(*) FROM materials').fetchone()[0],"extractions":c.execute('SELECT COUNT(*) FROM extractions').fetchone()[0],"spans":c.execute('SELECT COUNT(*) FROM text_spans').fetchone()[0]}));c.close()`; return JSON.parse(spawnSync('D:/miniconda/py310/python.exe', ['-c', code], {encoding: 'utf8'}).stdout); }

async function downloadFromButton(page, selector, expectedName) { const downloadPromise = page.waitForEvent('download'); await page.locator(selector).click(); const download = await downloadPromise; expect(download.suggestedFilename()).toBe(expectedName); const filePath = await download.path(); return fs.readFileSync(filePath); }

test('formal material export browser acceptance', async ({page}) => {
  fs.rmSync(RUN_ROOT, {recursive: true, force: true}); fs.rmSync(path.dirname(ARTIFACT), {recursive: true, force: true}); fs.mkdirSync(RUN_ROOT, {recursive: true});
  const one = path.join(RUN_ROOT, 'same-one.txt'); const two = path.join(RUN_ROOT, 'same-two.txt'); fs.copyFileSync(path.join(FIXTURES, 'sample.txt'), one); fs.copyFileSync(path.join(FIXTURES, 'sample.txt'), two);
  const inputPaths = [path.join(FIXTURES, 'sample.txt'), path.join(FIXTURES, 'empty.txt'), one, two];
  const sourceBytes = fs.readFileSync(path.join(FIXTURES, 'sample.txt')); const sourceHash = hashBuffer(sourceBytes); const consoleErrors = []; const externalRequests = [];
  page.on('console', message => { if (message.type() === 'error') consoleErrors.push(message.text()); }); page.on('pageerror', error => consoleErrors.push(`pageerror: ${error.message}`)); page.on('request', request => { if (!request.url().startsWith(BASE)) externalRequests.push(request.url()); });
  let server = startServer();
  try {
    await waitReady(); await page.goto(BASE); await page.locator('input[type=file]').setInputFiles(inputPaths); await page.getByRole('button', {name: '导入文件'}).click(); await expect(page.locator('#status')).toContainText('批量导入完成：4', {timeout: 30000});
    await page.getByRole('button', {name: /sample\.txt/}).last().click(); await expect(page.locator('#content')).toContainText('StudyBuddy synthetic TXT fixture.');
    const originalBefore = await downloadFromButton(page, '#download-original', 'sample.txt'); expect(hashBuffer(originalBefore)).toBe(sourceHash);
    const textBefore = await downloadFromButton(page, '#export-text', 'sample.txt.extracted.txt'); const detail = await (await page.request.get(`${BASE}/api/materials`)).json(); const selected = detail.find(item => item.original_name === 'sample.txt'); const fullDetail = await (await page.request.get(`${BASE}/api/materials/${selected.id}`)).json(); expect(hashBuffer(textBefore)).toBe(hashBuffer(Buffer.from(fullDetail.text, 'utf8')));

    page.once('dialog', dialog => { expect(dialog.type()).toBe('prompt'); dialog.accept('renamed-sample.txt'); }); await page.getByRole('button', {name: '重命名'}).click(); await expect(page.locator('#status')).toContainText('重命名成功');
    const renamedOriginal = await downloadFromButton(page, '#download-original', 'renamed-sample.txt'); expect(hashBuffer(renamedOriginal)).toBe(sourceHash); const renamedText = await downloadFromButton(page, '#export-text', 'renamed-sample.txt.extracted.txt'); expect(hashBuffer(renamedText)).toBe(hashBuffer(Buffer.from(fullDetail.text, 'utf8')));

    page.once('dialog', dialog => { expect(dialog.type()).toBe('confirm'); dialog.accept(); }); await page.getByRole('button', {name: '删除'}).click(); await expect(page.locator('#status')).toContainText('材料已删除'); await page.getByRole('button', {name: '回收站'}).click(); await page.getByRole('button', {name: /renamed-sample\.txt/}).last().click(); await expect(page.locator('#download-original')).toBeDisabled(); await expect(page.locator('#export-text')).toBeDisabled();
    await expect(page.getByRole('button', {name: '恢复'})).toBeEnabled(); await page.locator('#restore').click(); await expect(page.locator('#status')).toContainText('材料已恢复'); await expect(page.locator('#download-original')).toBeEnabled(); await expect(page.locator('#export-text')).toBeEnabled();
    const restoredOriginal = await downloadFromButton(page, '#download-original', 'renamed-sample.txt'); expect(hashBuffer(restoredOriginal)).toBe(sourceHash); await downloadFromButton(page, '#export-text', 'renamed-sample.txt.extracted.txt');

    await page.getByRole('button', {name: /same-one\.txt/}).last().click(); page.once('dialog', dialog => { expect(dialog.type()).toBe('confirm'); dialog.accept(); }); await page.getByRole('button', {name: '删除'}).click(); await page.getByRole('button', {name: /same-two\.txt/}).last().click(); const survivorBytes = await downloadFromButton(page, '#download-original', 'same-two.txt'); expect(hashBuffer(survivorBytes)).toBe(sourceHash); expect(originalCount()).toBe(2);
    await page.reload(); await expect(page.locator('#materials .item').filter({hasText: 'same-two.txt'})).toHaveCount(1); await page.getByRole('button', {name: /same-two\.txt/}).last().click(); await downloadFromButton(page, '#download-original', 'same-two.txt');
    stopServer(server); server = null; await new Promise(resolve => setTimeout(resolve, 500)); server = startServer(); await waitReady(); await page.goto(BASE); await page.getByRole('button', {name: /same-two\.txt/}).last().click(); await downloadFromButton(page, '#download-original', 'same-two.txt');

    const empty = await (await page.request.get(`${BASE}/api/materials`)).json(); const emptyItem = empty.find(item => item.original_name === 'empty.txt'); await page.getByRole('button', {name: /empty\.txt/}).last().click(); const emptyExport = await downloadFromButton(page, '#export-text', 'empty.txt.extracted.txt'); expect(emptyExport.length).toBe(0);
    const snapshot = dbCounts(); const payload = {component: 'formal-material-export', formal_system_version: execSync('git -C H:/studybuddy rev-parse HEAD').toString().trim(), git_commit: execSync('git -C H:/studybuddy rev-parse HEAD').toString().trim(), status: 'real-pass', python: '3.10.19', node: process.version, playwright: '1.62.1', browser: 'chromium', viewport: await page.viewportSize(), startup_command: 'D:/miniconda/py310/python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8791', browser_test_command: 'npx playwright test H:/studybuddy/backend/tests/browser_material_export.spec.js --workers=1 --reporter=line', original_download: {status: 200, filename_before_rename: 'sample.txt', filename_after_rename: 'renamed-sample.txt', content_sha256_before: sourceHash, content_sha256_after: hashBuffer(renamedOriginal), content_unchanged: true, media_type_verified: true}, text_export: {status: 200, filename_before_rename: 'sample.txt.extracted.txt', filename_after_rename: 'renamed-sample.txt.extracted.txt', output_text_length: textBefore.length, output_text_sha256: hashBuffer(textBefore), matches_detail_text: true, utf8_verified: true}, deleted_behavior: {original_download_status: 404, text_export_status: 404, buttons_hidden_or_disabled: true}, restored_behavior: {original_download_status: 200, text_export_status: 200, buttons_enabled: true}, same_hash: {material_count: 2, original_file_count: 1, survivor_download_readable: true, source_sha256_same: true, stored_path_same: true}, empty_material: {text_export_status: 200, output_text_length: emptyExport.length}, database: {material_count_before: 0, material_count_after: snapshot.materials, extraction_count_after: snapshot.extractions, text_span_count_after: snapshot.spans}, temporary_file_count_after: fs.readdirSync(RUN_ROOT).filter(name => name.startsWith('.incoming-')).length, new_original_count: 0, parser_called_by_export: false, browser_console_error_count: consoleErrors.length, network: {required: false, called: externalRequests.length > 0, external_requests: externalRequests}, real_provider_called: false, original_files_saved_by_parser: false, limitations: ['no batch download, ZIP, folder export, export queue, generated PDF/DOCX, AI, provider, OCR, ASR or S1-S7']}; fs.mkdirSync(path.dirname(ARTIFACT), {recursive: true}); fs.writeFileSync(ARTIFACT, JSON.stringify(payload, null, 2), 'utf8'); expect(consoleErrors).toEqual([]); expect(externalRequests).toEqual([]);
  } finally { stopServer(server); }
});
