const { test, expect } = require('@playwright/test');
const { spawn } = require('child_process');
const fs = require('fs');
const RUN_ROOT = 'H:/studybuddy-test/runs/p1-5-4-browser';
const PORT = 8834; const BASE = `http://127.0.0.1:${PORT}`; let server;
function start(){const env={...process.env,PYTHONPATH:'H:/studybuddy/backend',STUDYBUDDY_DATA_ROOT:RUN_ROOT,STUDYBUDDY_AI_PROVIDER:'fake'};return spawn('C:/miniconda/py310/python.exe',['-m','uvicorn','app.main:app','--host','127.0.0.1','--port',String(PORT)],{cwd:'H:/studybuddy/backend',env,stdio:'ignore',windowsHide:true})}
async function ready(){await expect.poll(async()=>{try{return(await fetch(`${BASE}/api/readiness`)).ok}catch(_){return false}},{timeout:15000}).toBe(true)}
async function open(page){await page.goto(`${BASE}/app/settings-provider.html`);await expect(page.locator('#provider-test')).toBeVisible()}
function noLeak(page,s){return page.evaluate(secret=>({text:document.body.innerText,html:document.documentElement.outerHTML,url:location.href,history:JSON.stringify(history.state),cookie:document.cookie,local:JSON.stringify(localStorage),session:JSON.stringify(sessionStorage)}),s).then(x=>Object.values(x).every(v=>!v.includes(s)))}
test.beforeEach(async()=>{fs.rmSync(RUN_ROOT,{recursive:true,force:true});server=start();await ready()});test.afterEach(()=>{if(server&&!server.killed)server.kill();server=null});

test('P1-5-4 structure is test-then-save and does not auto-call connection tests',async({page})=>{let calls=[];await page.route('**/api/system/**',route=>{calls.push(route.request().url());return route.continue()});await open(page);await expect(page.locator('body')).toContainText('先测后存');await expect(page.locator('body')).toContainText('不进入备份');await expect(page.locator('#provider-test')).toBeVisible();await expect(page.locator('#email-test')).toBeVisible();await expect(page.locator('input[type=password]')).toHaveCount(3);for(const input of await page.locator('input[type=password]').all())expect(await input.getAttribute('autocomplete')).toBe('off');expect(await page.locator('input[type=password]').evaluateAll(xs=>xs.every(x=>x.spellcheck===false))).toBe(true);expect(calls.filter(x=>x.includes('connection-test'))).toEqual([]);expect(calls.filter(x=>x.includes('/api/system/settings'))).toEqual([]);await expect(page.locator('#provider-save')).toBeHidden();await expect(page.locator('#email-save')).toBeHidden()});

test('P1-5-4 provider success uses provider_id for export and clears key',async({page})=>{await page.addInitScript(() => { Object.defineProperty(Navigator.prototype, 'clipboard', { configurable: true, get: () => ({ writeText: async text => { window.__clip = text; } }) }); });let body;await page.route('**/api/system/provider-connection-test',async route=>{body=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:'{"status":"ok"}'})});await open(page);await page.locator('#provider-id').fill('synthetic-provider');await page.locator('#provider-model').fill('synthetic-model');await page.locator('#provider-url').fill('https://loopback.invalid/v1');await page.locator('#provider-key').fill('TEST_SECRET_DO_NOT_LEAK_7d0f');await page.locator('#provider-form').evaluate(f=>f.requestSubmit());await expect(page.locator('#provider-result')).toContainText('测试通过');await expect(page.locator('#provider-save')).toBeVisible();await expect.poll(()=>body).toMatchObject({provider_type:'llm',model_id:'synthetic-model',base_url:'https://loopback.invalid/v1'});expect(body.api_key).toBe('TEST_SECRET_DO_NOT_LEAK_7d0f');await expect(page.locator('#provider-key')).toHaveValue('');expect(await noLeak(page,'TEST_SECRET_DO_NOT_LEAK_7d0f')).toBe(true);await page.reload();await page.evaluate(()=>{window.__clip=''});await page.locator('#provider-id').fill('synthetic-provider');await page.locator('#provider-model').fill('synthetic-model');await page.locator('#provider-url').fill('https://loopback.invalid/v1');await page.locator('#provider-key').fill('TEST_SECRET_DO_NOT_LEAK_7d0f');await page.locator('#provider-copy').click();const clip=await page.evaluate(()=>window.__clip);expect(clip).toContain('STUDYBUDDY_AI_PROVIDER=synthetic-provider');expect(clip).not.toContain('llm');expect(clip).toContain('STUDYBUDDY_AI_API_KEY=TEST_SECRET_DO_NOT_LEAK_7d0f');await expect(page.locator('#provider-key')).toHaveValue('');expect(await noLeak(page,'TEST_SECRET_DO_NOT_LEAK_7d0f')).toBe(true)});

test('P1-5-4 provider failures map safely and clear key',async({page})=>{for(const code of ['provider_auth_failed','provider_timeout','provider_response_too_large']){await page.route('**/api/system/provider-connection-test',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({detail:code})}));await open(page);await page.locator('#provider-id').fill('synthetic-provider');await page.locator('#provider-model').fill('synthetic-model');await page.locator('#provider-url').fill('https://loopback.invalid/v1');await page.locator('#provider-key').fill('TEST_SECRET_DO_NOT_LEAK_7d0f');await page.locator('#provider-form').evaluate(f=>f.requestSubmit());await expect(page.locator('#provider-result')).toBeVisible();await expect(page.locator('#provider-key')).toHaveValue('');expect(await noLeak(page,'TEST_SECRET_DO_NOT_LEAK_7d0f')).toBe(true);await page.unrouteAll({behavior:'ignoreErrors'})}});

test('P1-5-4 email channels use typed payloads and clear secrets',async({page})=>{let body;await page.route('**/api/system/email-connection-test',async route=>{body=route.request().postDataJSON();await route.fulfill({status:200,contentType:'application/json',body:'{"status":"ok"}'})});await open(page);await page.locator('#smtp-username').fill('synthetic-user');await page.locator('#smtp-password').fill('TEST_SMTP_PASSWORD_DO_NOT_LEAK_29ce');await page.locator('#smtp-sender').fill('sender@example.test');await page.locator('#smtp-recipient').fill('recipient@example.test');await page.locator('#email-form').evaluate(f=>f.requestSubmit());await expect.poll(()=>body).toMatchObject({channel:'smtp',smtp_secure:true,smtp_port:465});expect(typeof body.smtp_port).toBe('number');await expect(page.locator('#smtp-password')).toHaveValue('');expect(await noLeak(page,'TEST_SMTP_PASSWORD_DO_NOT_LEAK_29ce')).toBe(true);await page.locator('#email-channel').selectOption('feishu');await expect(page.locator('#smtp-fields')).toBeHidden();await page.locator('#feishu-webhook').fill('https://open.feishu.cn/hook/TEST_WEBHOOK_DO_NOT_LEAK_5a21');await page.locator('#email-test').click();await expect.poll(()=>body).toMatchObject({channel:'feishu'});expect(body.feishu_webhook).toContain('TEST_WEBHOOK_DO_NOT_LEAK_5a21');await expect(page.locator('#feishu-webhook')).toHaveValue('');expect(await noLeak(page,'TEST_WEBHOOK_DO_NOT_LEAK_5a21')).toBe(true)});

test('P1-5-4 refresh and clipboard rejection do not restore secrets',async({page})=>{await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('clipboard unavailable')}}})});await open(page);await page.reload();await page.locator('#provider-id').fill('synthetic-provider');await page.locator('#provider-model').fill('synthetic-model');await page.locator('#provider-url').fill('https://loopback.invalid/v1');await page.locator('#provider-key').fill('TEST_SECRET_DO_NOT_LEAK_7d0f');await page.locator('#provider-copy').click();await expect(page.locator('#provider-result')).toContainText('无法访问剪贴板');await expect(page.locator('#provider-key')).toHaveValue('');expect(await noLeak(page,'TEST_SECRET_DO_NOT_LEAK_7d0f')).toBe(true);await page.locator('#provider-key').fill('TEST_SECRET_DO_NOT_LEAK_7d0f');await page.reload();await expect(page.locator('#provider-key')).toHaveValue('');expect(await noLeak(page,'TEST_SECRET_DO_NOT_LEAK_7d0f')).toBe(true);await page.goto(`${BASE}/app/settings.html`);await page.goBack();await expect(page.locator('#provider-key')).toHaveValue('');expect(await noLeak(page,'TEST_SECRET_DO_NOT_LEAK_7d0f')).toBe(true)});

test('P2-USE-3 save appears only after a passing test and persists without echoing the key',async({page})=>{let saved;await page.route('**/api/system/provider-connection-test',route=>route.fulfill({status:200,contentType:'application/json',body:'{"status":"ok"}'}));await page.route('**/api/system/settings',async route=>{if(route.request().method()==='PUT'){saved=route.request().postDataJSON();return route.fulfill({status:200,contentType:'application/json',body:'{"settings":{"ai_api_key_set":true},"capabilities":{},"ready_count":0,"total_count":7}'})}return route.continue()});await open(page);await expect(page.locator('#provider-save')).toBeHidden();await page.locator('#provider-id').fill('synthetic-provider');await page.locator('#provider-model').fill('synthetic-model');await page.locator('#provider-url').fill('https://loopback.invalid/v1');await page.locator('#provider-key').fill('TEST_SECRET_DO_NOT_LEAK_7d0f');await page.locator('#provider-form').evaluate(f=>f.requestSubmit());await expect(page.locator('#provider-save')).toBeVisible();await page.locator('#provider-save').click();await expect(page.locator('#provider-result')).toContainText('\u5df2\u4fdd\u5b58');await expect.poll(()=>saved).toMatchObject({ai_provider_id:'synthetic-provider',ai_model_id:'synthetic-model',ai_base_url:'https://loopback.invalid/v1'});expect(saved.ai_api_key).toBe('TEST_SECRET_DO_NOT_LEAK_7d0f');await expect(page.locator('#provider-save')).toBeHidden();await expect(page.locator('#provider-key')).toHaveValue('');expect(await noLeak(page,'TEST_SECRET_DO_NOT_LEAK_7d0f')).toBe(true)});

test('P2-USE-3 editing a verified form withdraws the save affordance',async({page})=>{await page.route('**/api/system/provider-connection-test',route=>route.fulfill({status:200,contentType:'application/json',body:'{"status":"ok"}'}));await open(page);await page.locator('#provider-id').fill('synthetic-provider');await page.locator('#provider-model').fill('synthetic-model');await page.locator('#provider-url').fill('https://loopback.invalid/v1');await page.locator('#provider-key').fill('TEST_SECRET_DO_NOT_LEAK_7d0f');await page.locator('#provider-form').evaluate(f=>f.requestSubmit());await expect(page.locator('#provider-save')).toBeVisible();await page.locator('#provider-model').fill('changed-model');await expect(page.locator('#provider-save')).toBeHidden()});

test('P2-USE-3 email save stores credentials but never switches delivery on',async({page})=>{let saved;await page.route('**/api/system/email-connection-test',route=>route.fulfill({status:200,contentType:'application/json',body:'{"status":"ok"}'}));await page.route('**/api/system/settings',async route=>{if(route.request().method()==='PUT'){saved=route.request().postDataJSON();return route.fulfill({status:200,contentType:'application/json',body:'{"settings":{},"capabilities":{},"ready_count":0,"total_count":7}'})}return route.continue()});await open(page);await expect(page.locator('#email-save')).toBeHidden();await page.locator('#smtp-username').fill('sender@example.test');await page.locator('#smtp-password').fill('TEST_SMTP_PASSWORD_DO_NOT_LEAK_29ce');await page.locator('#smtp-sender').fill('sender@example.test');await page.locator('#smtp-recipient').fill('recipient@example.test');await page.locator('#email-form').evaluate(f=>f.requestSubmit());await expect(page.locator('#email-save')).toBeVisible();await page.locator('#email-save').click();await expect(page.locator('#email-result')).toContainText('\u5df2\u4fdd\u5b58');await expect.poll(()=>saved).toMatchObject({report_delivery_smtp_host:'smtp.qq.com',report_delivery_smtp_port:465,report_delivery_smtp_secure:true,report_delivery_smtp_targets:'primary=recipient@example.test'});expect(saved.report_delivery_smtp_password).toBe('TEST_SMTP_PASSWORD_DO_NOT_LEAK_29ce');expect(Object.keys(saved)).not.toContain('report_delivery_mode');expect(Object.keys(saved)).not.toContain('report_delivery_enabled');expect(Object.keys(saved)).not.toContain('report_delivery_authorized');await expect(page.locator('#smtp-password')).toHaveValue('');expect(await noLeak(page,'TEST_SMTP_PASSWORD_DO_NOT_LEAK_29ce')).toBe(true)});

test('P2-USE-6 local component form saves with its own default selections against a live server',async({page})=>{
  await page.goto(`${BASE}/app/settings.html`);
  await expect(page.locator('#local-save')).toBeVisible();
  // Default state: OCR switch on "follow detection", every path blank.
  await expect(page.locator('#ocr-enabled')).toHaveValue('');
  await page.locator('#local-form').evaluate(f=>f.requestSubmit());
  await expect(page.locator('#local-result')).toContainText('已保存');
  await expect(page.locator('#local-result')).toHaveClass(/status-success/);
  // A forced switch plus a path also round-trips, and the path is never echoed.
  await page.locator('#ocr-enabled').selectOption('false');
  await page.locator('#ocr-root').fill('models/ocr');
  await page.locator('#local-form').evaluate(f=>f.requestSubmit());
  await expect(page.locator('#local-result')).toContainText('已保存');
  await page.reload();
  await expect(page.locator('#ocr-enabled')).toHaveValue('false');
  await expect(page.locator('#ocr-root')).toHaveValue('');
  await expect(page.locator('#ocr-root')).toHaveAttribute('placeholder',/已设置/);
  expect(await noLeak(page,'models/ocr')).toBe(true);
  // Clearing the override returns the switch to "follow detection".
  await page.locator('#local-clear').click();
  await expect(page.locator('#local-result')).toContainText('已清除');
  await expect(page.locator('#ocr-enabled')).toHaveValue('');
});
