const { test, expect } = require('@playwright/test');
const { spawn } = require('child_process');
const path = require('path');
const fixture = path.resolve('H:/studybuddy-test/fixtures/kaobuddy-foundation/sample.txt');
const folderFixture = path.resolve('H:/studybuddy-test/fixtures/kaobuddy-foundation');
const BASE = 'http://127.0.0.1:8791';
let server;
test.beforeEach(async () => { server = spawn('D:/miniconda/py310/python.exe', ['-m', 'uvicorn', 'app.main:app', '--host', '127.0.0.1', '--port', '8791'], { cwd: 'H:/studybuddy/backend', env: {...process.env, PYTHONPATH: 'H:/studybuddy/backend', STUDYBUDDY_DATA_ROOT: 'H:/studybuddy-test/runs/formal-frontend-failure-contract'}, stdio: 'ignore', windowsHide: true }); await expect.poll(async () => { try { return (await fetch(`${BASE}/api/health`)).ok; } catch (_) { return false; } }, { timeout: 15000 }).toBe(true); });
test.afterEach(() => { if (server && !server.killed) server.kill(); server = null; });
const forbidden = ['stored_path', 'traceback', 'database is locked', 'C:/secret', 'internal backend text'];
async function assertSafe(page){const text=(await page.locator('body').innerText()).toLowerCase();for(const value of forbidden)expect(text).not.toContain(value.toLowerCase())}
async function load(page){await page.goto(BASE);await expect(page.locator('#status')).toBeVisible()}

test('single import failure restores controls and followup succeeds',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e));let fail=true;await page.route('**/api/materials',async route=>fail?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'material_persist_failed',path:'C:/secret',trace:'fake'})}):route.continue());await load(page);await page.locator('#file').setInputFiles(fixture);await page.locator('#file-import').click();await expect(page.locator('#status')).toHaveText('导入失败');await expect(page.locator('#file-import')).toBeEnabled();await assertSafe(page);fail=false;await page.locator('#file').setInputFiles(fixture);await page.locator('#file-import').click();await expect(page.locator('#status')).toContainText('导入完成');expect(errors).toHaveLength(0)})

test('folder failure is generic and controls restore',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e));await page.route('**/api/materials/batch',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'folder secret',stored_path:'C:/secret',traceback:'fake'})}));await load(page);await page.locator('#folder').setInputFiles(folderFixture);await page.locator('#folder-import').click();await expect(page.locator('#status')).toHaveText('文件夹导入失败');await expect(page.locator('#folder-import')).toBeEnabled();await assertSafe(page);expect(errors).toHaveLength(0)})

test('batch partial and malformed payload are safe',async({page})=>{let malformed=false;await page.route('**/api/materials/batch',route=>route.fulfill({status:201,contentType:'application/json',body:malformed?JSON.stringify({items:'bad'}):JSON.stringify({batch_id:'synthetic',total:3,success:1,empty:0,rejected:1,failed:1,items:[{original_name:'ok.txt',status:'success',material_id:null,warnings:[]},{original_name:'bad.txt',status:'rejected',error_code:'file_too_large',warnings:[]},{original_name:'failed.txt',status:'failed',error_code:'material_persist_failed',warnings:[]}]})}));await load(page);await page.locator('#file').setInputFiles([fixture,fixture]);await page.locator('#file-import').click();await expect(page.locator('#summary')).toContainText('总数 3');await expect(page.locator('#file-import')).toBeEnabled();await assertSafe(page);malformed=true;await page.locator('#file').setInputFiles([fixture,fixture]);await page.locator('#file-import').click();await expect(page.locator('#status')).toHaveText('导入失败');await expect(page.locator('#file-import')).toBeEnabled();await assertSafe(page)})

test('network rejection restores import controls',async({page})=>{await page.route('**/api/materials',route=>route.abort());await load(page);await page.locator('#file').setInputFiles(fixture);await page.locator('#file-import').click();await expect(page.locator('#status')).toHaveText('导入失败');await expect(page.locator('#file-import')).toBeEnabled();await assertSafe(page)})

async function importAndSelect(page){await load(page);await page.locator('#file').setInputFiles(fixture);await page.locator('#file-import').click();await expect(page.locator('#status')).toContainText('导入完成');await page.getByRole('button',{name:/sample\.txt/}).last().click();await expect(page.locator('#title')).toHaveText('sample.txt')}
async function moveToDeleted(page,name){page.once('dialog',dialog=>dialog.accept());await page.locator('#delete').click();await expect(page.locator('#status')).toHaveText('材料已删除');await page.locator('#deleted-view').click();await page.getByRole('button',{name:new RegExp(name.replace('.','\\.'))}).last().click();await expect(page.locator('#restore')).toBeEnabled()}

test('mutation failures preserve selection, unlock controls, and permit retry',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e));await importAndSelect(page);let renameFail=true;await page.route('**/api/materials/*',route=>route.request().method()==='PATCH'&&renameFail?route.fulfill({status:200,contentType:'text/plain',body:'not json'}):route.continue());page.once('dialog',d=>d.accept('renamed.txt'));await page.locator('#rename').click();await expect(page.locator('#status')).toHaveText('重命名失败');await expect(page.locator('#title')).toHaveText('sample.txt');await expect(page.locator('#rename')).toBeEnabled();renameFail=false;page.once('dialog',d=>d.accept('renamed.txt'));await page.locator('#rename').click();await expect(page.locator('#status')).toHaveText('重命名成功');await expect(page.locator('#title')).toHaveText('renamed.txt');await page.unroute('**/api/materials/*');let deletes=0;await page.route('**/api/materials/*',route=>route.request().method()==='DELETE'?(deletes++,route.fulfill({status:500,contentType:'text/plain',body:'private traceback'})):route.continue());page.once('dialog',d=>d.accept());await page.locator('#delete').click();await expect(page.locator('#status')).toHaveText('删除失败');await expect(page.locator('#title')).toHaveText('renamed.txt');await expect(page.locator('#delete')).toBeEnabled();expect(deletes).toBe(1);await page.unroute('**/api/materials/*');await moveToDeleted(page,'renamed.txt');await page.route('**/api/materials/*/restore',route=>route.fulfill({status:200,contentType:'text/plain',body:'not json'}));await page.locator('#restore').click();await expect(page.locator('#status')).toHaveText('恢复失败');await expect(page.locator('#title')).toHaveText('renamed.txt');await expect(page.locator('#restore')).toBeEnabled();await page.unroute('**/api/materials/*/restore');let purges=0;await page.route('**/api/materials/*/purge',route=>{purges++;return route.abort()});page.once('dialog',d=>d.accept());await page.locator('#purge').click();await expect(page.locator('#status')).toHaveText('永久删除失败');await expect(page.locator('#title')).toHaveText('renamed.txt');await expect(page.locator('#purge')).toBeEnabled();expect(purges).toBe(1);await assertSafe(page);expect(errors).toHaveLength(0)})

test('export failures do not download, unlock controls, and retry',async({page})=>{await importAndSelect(page);let downloads=0;page.on('download',()=>downloads++);await page.route('**/api/materials/*/original',route=>route.fulfill({status:500,contentType:'text/plain',body:'private traceback'}));await page.locator('#download-original').click();await expect(page.locator('#status')).toHaveText('原文件下载失败');await expect(page.locator('#download-original')).toBeEnabled();expect(downloads).toBe(0);await page.unroute('**/api/materials/*/original');const originalDownload=page.waitForEvent('download');await page.locator('#download-original').click();await originalDownload;await expect(page.locator('#status')).toHaveText('原文件下载完成');await page.route('**/api/materials/*/text',route=>route.abort());await page.locator('#export-text').click();await expect(page.locator('#status')).toHaveText('正文导出失败');await expect(page.locator('#export-text')).toBeEnabled();await page.unroute('**/api/materials/*/text');await page.locator('.material-select').last().check();let zipCalls=0;await page.route('**/api/materials/export',route=>{zipCalls++;return route.fulfill({status:200,contentType:'text/plain',body:'not a zip'})});await page.locator('#export-selected-bundle').click();await expect(page.locator('#status')).toHaveText('批量导出失败');await expect(page.locator('#export-selected-bundle')).toBeEnabled();expect(zipCalls).toBe(1);await assertSafe(page)})
