
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
const statusEl=document.querySelector('#status'),listEl=document.querySelector('#materials'),summaryEl=document.querySelector('#summary'),batchItemsEl=document.querySelector('#batch-items'),filterEl=document.querySelector('#filters');let currentFilter='';
function announce(message,kind='status'){statusEl.textContent=message;statusEl.className=`status ${kind==='error'?'error':kind==='success'?'success':''}`;const alertRoot=document.querySelector('#alert-root');alertRoot.textContent=kind==='error'?message:'';alertRoot.className=kind==='error'?'error':''}
function updateNavContext(){const view=viewMode==='deleted'?'回收站':'正常材料';const material=selectedMaterial?.original_name||'未选择材料';const thread=qaThreadId?` · 当前对话 ${document.querySelector('#qa-thread-title')?.textContent||'已选择'}`:'';const scope=qaScopeIds.length?` · 范围 ${qaScopeIds.length} 个材料`:'';document.querySelector('#nav-context').textContent=`${view} · ${material}${thread}${scope}`}
function setViewCurrent(){const active=viewMode==='active';document.querySelector('#active-view').setAttribute('aria-current',active?'page':'false');document.querySelector('#deleted-view').setAttribute('aria-current',active?'false':'page');updateNavContext()}
let viewMode='active';let currentQuery='';let providerCapabilities=null;let exportInFlight=false;let importInFlight=false;let currentOffset=0;let currentTotal=0;let currentHasMore=false;const PAGE_SIZE=20;
function textNode(tag, className, value){const node=document.createElement(tag);if(className)node.className=className;node.textContent=value;return node}
function renderMaterial(item, deleted){const button=document.createElement('button');button.className=`item${deleted?' deleted-item':''}`;button.dataset.id=item.id;button.setAttribute('aria-pressed',item.id===selectedMaterialId?'true':'false');if(!deleted){const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.className='material-select';checkbox.dataset.id=item.id;checkbox.setAttribute('aria-label',`选择材料 ${item.original_name}`);checkbox.addEventListener('click',event=>event.stopPropagation());button.append(checkbox,document.createTextNode(' '))}button.append(textNode('span','',item.original_name),document.createElement('br'));const meta=deleted?`已删除 · ${item.status} · ${item.deleted_at}`:`${item.status} · ${item.media_type} · ${item.text_length} 字 · ${item.span_count} spans${item.error_code?' · '+item.error_code:''}`;button.append(textNode('span','meta',meta),document.createElement('br'),textNode('span','meta',deleted?`${item.text_length} 字 · ${item.span_count} spans`:`${item.text_length} 字 · ${item.span_count} spans`));if(!deleted&&currentQuery){if(item.match_fields&&item.match_fields.length){const labels={original_name:'名称',text:'正文'};button.append(document.createElement('br'),textNode('span','search-match',`命中：${item.match_fields.map(field=>labels[field]||field).join('、')}`))}if(item.snippet){button.append(document.createElement('br'),textNode('span','search-snippet',item.snippet))}}button.onclick=()=>deleted?loadDeletedMaterial(item.id):loadMaterial(item.id);return button}
let listGeneration=0;
function activeMaterialsUrl(){return `/api/materials?${new URLSearchParams(Object.fromEntries([['status',currentFilter],['q',currentQuery],['limit',PAGE_SIZE],['offset',currentOffset]].filter(([,value])=>value!=='')))}`}
function updatePagination(){const page=currentTotal?Math.floor(currentOffset/PAGE_SIZE)+1:0;const pages=currentTotal?Math.ceil(currentTotal/PAGE_SIZE):0;document.querySelector('#page-info').textContent=pages?`第 ${page} 页 / 共 ${pages} 页 · 共 ${currentTotal} 项`:'共 0 项';document.querySelector('#page-prev').disabled=currentOffset===0;document.querySelector('#page-next').disabled=!currentHasMore}
function renderList(items,deleted){document.querySelector('#batch-export').style.display=deleted?'none':'flex';listEl.replaceChildren();if(!items.length){listEl.append(textNode('p','meta',deleted?'回收站为空':'暂无材料'))}else{items.forEach(item=>{if(!deleted)qaScopeMeta.set(item.id,item);listEl.append(renderMaterial(item,deleted))})}if(!deleted)renderQaScope()}
async function loadList(){const generation=++listGeneration;const deleted=viewMode==='deleted';const url=deleted?`/api/materials/deleted?limit=${PAGE_SIZE}&offset=${currentOffset}`:activeMaterialsUrl();try{const r=await fetch(url);if(!r.ok)throw new Error('list_load_failed');const payload=await r.json();const items=Array.isArray(payload)?payload:payload&&Array.isArray(payload.items)?payload.items:null;if(!items)throw new Error('list_payload_invalid');currentTotal=Array.isArray(payload)?items.length:Number.isFinite(payload.total)?payload.total:0;currentHasMore=Array.isArray(payload)?false:payload.has_more===true;if(generation!==listGeneration)return null;renderList(items,deleted);updatePagination();document.querySelector('#search-summary').textContent=!deleted&&currentQuery?`匹配 ${items.length}`:'';return items}catch(error){if(generation!==listGeneration)return null;announce('材料列表加载失败','error');return null}}
let selectedMaterialId=null;let selectedMaterial=null;let detailGeneration=0;let mutationInFlight=false;let uiGeneration=0;let qaInFlight=false;let qaThreadId=null;let qaScopeIds=[];let qaLastQuestion='';let qaLastError=null;let qaHistoryGeneration=0;const qaScopeMeta=new Map();let citationNavigationKey=null;
function selectedIds(){return [...document.querySelectorAll('.material-select:checked')].map(node=>node.dataset.id)}
function navigationState(){return {material:selectedMaterialId,thread:qaThreadId,scope:qaScopeIds.slice(),citation:citationNavigationKey}}
function writeNavigation(replace=false){const params=new URLSearchParams();const state=navigationState();if(state.material)params.set('material',state.material);if(state.thread)params.set('thread',state.thread);if(state.scope.length)params.set('scope',state.scope.join(','));if(state.citation)params.set('citation',state.citation);const url=params.toString()?`${location.pathname}?${params.toString()}`:location.pathname;history[replace?'replaceState':'pushState']({},'',url)}
function readNavigation(){const params=new URLSearchParams(location.search);return {material:params.get('material'),thread:params.get('thread'),scope:(params.get('scope')||'').split(',').filter(Boolean),citation:params.get('citation')}}
function enterQa(push=true){const selected=selectedIds();if(selected.length)qaScopeIds=selected;if(!qaScopeIds.length&&selectedMaterialId)qaScopeIds=[selectedMaterialId];if(!selectedMaterialId)return;document.querySelector('#qa').scrollIntoView({block:'start'});renderQaScope();document.querySelector('#qa-question').focus();document.querySelector('#nav-qa').setAttribute('aria-current','page');document.querySelector('#nav-materials').setAttribute('aria-current','false');if(push)writeNavigation(false);refreshQaIndex();updateNavContext()}
function returnToMaterial(){document.querySelector('#content').scrollIntoView({block:'start'});writeNavigation(false);document.querySelector('#nav-materials').setAttribute('aria-current','page');document.querySelector('#nav-qa').setAttribute('aria-current','false');document.querySelector('#open-qa').focus();updateNavContext()}
async function handleNavigation(){const state=readNavigation();if(state.scope.length)qaScopeIds=state.scope;qaThreadId=state.thread;citationNavigationKey=null;if(state.material){await loadMaterial(state.material,true);if(state.citation)await locateCitation(state.citation,true)}else{document.querySelector('#qa').scrollIntoView({block:'start'});if(state.thread)await loadQaHistory(state.thread);else renderQaScope()}}
function setExportBusy(busy){exportInFlight=busy;['export-selected-originals','export-selected-text','export-selected-bundle','select-all','download-original','export-text'].forEach(id=>document.querySelector('#'+id).disabled=busy||viewMode==='deleted'||((id==='download-original'||id==='export-text')&&!selectedMaterialId))}
function currentUi(){return {view:viewMode,id:selectedMaterialId,generation:uiGeneration,threadId:qaThreadId,scopeIds:qaScopeIds.slice()}}
function stillCurrent(context){return context.view===viewMode&&context.id===selectedMaterialId&&context.generation===uiGeneration&&(!('threadId' in context)||context.threadId===qaThreadId)&&(!context.scopeIds||context.scopeIds.join('')===qaScopeIds.join(''))}
async function readJsonObject(response){let value;try{value=await response.json()}catch(_){throw Error('invalid_json_response')}if(!value||typeof value!=='object'||Array.isArray(value))throw Error('invalid_json_response');return value}
async function saveDownload(response,filename,zip){const contentType=(response.headers.get('content-type')||'').toLowerCase();if(zip&&!contentType.includes('application/zip'))throw Error('invalid_zip_response');const blob=await response.blob();if(zip){const signature=new Uint8Array(await blob.slice(0,4).arrayBuffer());if(signature.length!==4||signature[0]!==0x50||signature[1]!==0x4b||signature[2]!==0x03||signature[3]!==0x04)throw Error('invalid_zip_body')}const url=URL.createObjectURL(blob);try{const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click()}finally{URL.revokeObjectURL(url)}}
async function exportSelected(includeOriginal,includeText){if(exportInFlight||viewMode==='deleted')return;const ids=selectedIds();if(!ids.length){announce('请选择至少一个材料','error');return}const context=currentUi();setExportBusy(true);try{const r=await fetch('/api/materials/export',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({material_ids:ids,include_original:includeOriginal,include_text:includeText})});if(!r.ok){if(stillCurrent(context))announce(r.status===413?'导出文件过大':'批量导出失败','error');return}await saveDownload(r,'studybuddy-materials.zip',true);if(stillCurrent(context))announce('批量导出完成','success')}catch(_){if(stillCurrent(context))statusEl.textContent='批量导出失败'}finally{setExportBusy(false)}}
function setMutationBusy(busy){mutationInFlight=busy;document.querySelector('#rename').disabled=busy||viewMode==='deleted'||!selectedMaterialId;document.querySelector('#delete').disabled=busy||viewMode==='deleted'||!selectedMaterialId;document.querySelector('#restore').disabled=busy||viewMode!=='deleted'||!selectedMaterialId;document.querySelector('#purge').disabled=busy||viewMode!=='deleted'||!selectedMaterialId;document.querySelector('#download-original').disabled=busy||viewMode!=='active'||!selectedMaterialId;document.querySelector('#export-text').disabled=busy||viewMode!=='active'||!selectedMaterialId;}
function toast(message,kind='status'){const root=document.querySelector('#toast-root');root.replaceChildren();const node=textNode('div','toast',message);node.setAttribute('role',kind==='error'?'alert':'status');node.setAttribute('aria-live',kind==='error'?'assertive':'polite');root.append(node);setTimeout(()=>{if(root.contains(node))root.replaceChildren()},2600)}
function providerStatusMessage(data){if(!data||typeof data!=='object')return ['AI Provider 状态不可用','无法读取运行配置'];const provider=data.provider_id,model=data.model_id;const name=provider&&model?`${provider} · ${model}`:'';if(data.status==='demo')return ['AI Provider：演示模式',`${name} · deterministic/demo provider，不代表真实 AI 服务`];if(data.status==='not_configured')return ['AI 服务尚未配置','材料管理仍可使用；配置真实 Provider 后才能进行真实问答'];if(data.status==='invalid_config')return ['AI Provider 配置不完整','请检查运行配置'];if(data.status==='configured'&&data.verification_status==='not_verified')return ['AI Provider：已配置，尚未验证',`${name} · 未证明当前 endpoint/model 可用`];if(data.status==='temporarily_unavailable')return ['AI Provider：暂时不可用',`${name||'当前配置'} · 请稍后重试`];return ['AI Provider：状态未知',name||'请检查运行配置']}
function renderProviderStatus(data){providerCapabilities=data;const [title,detail]=providerStatusMessage(data);document.querySelector('#provider-status-title').textContent=title;document.querySelector('#provider-status-detail').textContent=detail;document.querySelector('#provider-status').classList.toggle('provider-status-error',data&&['invalid_config','temporarily_unavailable'].includes(data.status))}
async function loadProviderCapabilities(){try{const response=await fetch('/api/ai/capabilities');const data=await readJsonObject(response);renderProviderStatus(data)}catch(_){renderProviderStatus({status:'temporarily_unavailable',provider_id:null,model_id:null})}}
function setQaStatus(message,kind='meta'){const node=document.querySelector('#qa-status');node.className=`${kind==='error'?'meta error':'meta'}`;node.setAttribute('role',kind==='error'?'alert':'status');node.setAttribute('aria-live',kind==='error'?'assertive':'polite');node.textContent=message;updateNavContext()}
function clearQa(preserveContext=false){if(!preserveContext){qaThreadId=null;qaScopeIds=[];qaLastQuestion='';citationNavigationKey=null}qaInFlight=false;qaLastError=null;document.querySelector('#qa-question').value='';document.querySelector('#qa-question').disabled=true;document.querySelector('#qa-ask').disabled=true;document.querySelector('#ai-index').disabled=true;document.querySelector('#qa-index').disabled=true;document.querySelector('#qa-retry').hidden=true;document.querySelector('#qa-thread-title').textContent=qaThreadId?'正在恢复对话':'新对话';document.querySelector('#qa-thread-status').textContent='尚未发送问题';setQaStatus('选择已建立 AI 索引的正常材料后可提问');document.querySelector('#qa-answer').replaceChildren();document.querySelector('#qa-citations').replaceChildren();document.querySelector('#qa-timeline').replaceChildren(textNode('div','meta qa-empty','新对话尚未有消息'));document.querySelector('#qa-history-list').replaceChildren();document.querySelector('#qa-history-status').textContent='请选择材料';renderQaScope()}
function renderQaScope(){const list=document.querySelector('#qa-scope-list');list.replaceChildren();const boxes=[...document.querySelectorAll('.material-select')];const current=selectedMaterialId;const ids=qaScopeIds.length?qaScopeIds:(current?[current]:[]);qaScopeIds=ids.filter(id=>boxes.some(box=>box.dataset.id===id)||id===current||qaScopeMeta.has(id));boxes.forEach(box=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.checked=qaScopeIds.includes(box.dataset.id);input.addEventListener('change',()=>{qaScopeIds=[...document.querySelectorAll('#qa-scope-list input:checked')].map(node=>node.value);writeNavigation(true);renderQaScope();refreshQaIndex()});input.value=box.dataset.id;const item=qaScopeMeta.get(box.dataset.id);label.append(input,document.createTextNode(item?.original_name||box.closest('.item')?.querySelector('span')?.textContent||box.dataset.id));list.append(label)});qaScopeIds.filter(id=>!boxes.some(box=>box.dataset.id===id)).forEach(id=>{const item=qaScopeMeta.get(id);const label=textNode('div','meta',`${item?.original_name||id} · 当前列表未显示`);list.append(label)});document.querySelector('#qa-scope-summary').textContent=qaScopeIds.length?`已选择 ${qaScopeIds.length} 个材料`:'未选择材料';updateNavContext()}
function setQaScopeToCurrent(){qaScopeIds=selectedMaterialId?[selectedMaterialId]:[];writeNavigation(true);renderQaScope();refreshQaIndex();toast('已切换到当前材料')}
async function restoreNavigation(){const state=readNavigation();if(state.scope.length)qaScopeIds=state.scope;qaThreadId=state.thread;citationNavigationKey=state.citation;if(state.material)await loadMaterial(state.material,true);else if(state.thread)await loadQaHistory(state.thread)}
function closeCitationDialog(){document.querySelector('#qa-dialog-root').replaceChildren()}
function showCitationDialog(data){const root=document.querySelector('#qa-dialog-root');const returnFocus=document.activeElement;root.replaceChildren();const backdrop=document.createElement('div');backdrop.className='dialog-backdrop';const dialog=document.createElement('div');dialog.className='dialog';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-labelledby','citation-dialog-title');const title=textNode('h3','', '引用详情');title.id='citation-dialog-title';const body=textNode('div','',`状态：${data.status==='valid'?'可用':data.status==='source_deleted'?'来源已删除':'来源已不可用'}
材料：${data.material_name||data.material_id||'未知'}
Revision：${data.revision_id||'未知'}
Chunk：${data.chunk_id||'未知'}
${data.excerpt?'摘录：'+data.excerpt:''}`);body.style.whiteSpace='pre-wrap';const close=document.createElement('button');close.type='button';close.textContent='关闭';const closeDialog=()=>{root.replaceChildren();document.removeEventListener('keydown',onKeydown);if(returnFocus&&typeof returnFocus.focus==='function')returnFocus.focus()};const onKeydown=event=>{if(event.key==='Escape')closeDialog()};close.onclick=closeDialog;dialog.append(title,body,close);backdrop.append(dialog);backdrop.onclick=event=>{if(event.target===backdrop)closeDialog()};root.append(backdrop);document.addEventListener('keydown',onKeydown);close.focus()}
function renderHistory(data){const timeline=document.querySelector('#qa-timeline');const answer=document.querySelector('#qa-answer');const citations=document.querySelector('#qa-citations');timeline.replaceChildren();answer.replaceChildren();citations.replaceChildren();const messages=data.messages||[];const latestAnswer=messages.slice().reverse().find(message=>message.role==='assistant');answer.textContent=latestAnswer?.content||'';if(!messages.length)timeline.append(textNode('div','meta qa-empty','新对话尚未有消息'));messages.forEach(message=>{const row=textNode('article',`qa-message qa-message-${message.role}`,'');row.append(textNode('div','qa-message-label',message.role==='user'?'你的问题':'AI 回答'));row.append(textNode('div',message.role==='user'?'qa-message-user':'qa-message-assistant',message.content||''));if(message.answer_status&&message.answer_status!=='ready')row.classList.add('qa-message-failed');if(message.citations){const citeRow=textNode('div','qa-citations','');message.citations.forEach(citation=>{const button=document.createElement('button');button.type='button';button.textContent=citation.status==='valid'?`引用 ${citation.position} · ${citation.material_name||'来源'}`:`引用 ${citation.position} · 来源不可用`;button.setAttribute('aria-label',button.textContent);button.onclick=()=>openCitation(citation);citeRow.append(button)});row.append(citeRow)}timeline.append(row)});const thread=data.thread||{};document.querySelector('#qa-thread-title').textContent=thread.title||'新对话';document.querySelector('#qa-thread-status').textContent=messages.length?`${messages.length} 条消息 · 最近更新 ${thread.updated_at||'未知时间'}`:'尚未发送问题';document.querySelector('#qa-empty')?.remove();setQaStatus(messages.length?'已加载问答历史':'新对话尚未有消息');updateNavContext();document.querySelector('#qa-question').focus()}
async function loadQaHistory(threadId){const generation=++qaHistoryGeneration;uiGeneration++;const context={generation,threadId};document.querySelector('#qa-thread-status').textContent='正在加载对话';document.querySelector('#qa-timeline').replaceChildren(textNode('div','meta qa-empty','正在加载对话'));try{const response=await fetch(`/api/qa/threads/${encodeURIComponent(threadId)}`);const data=await readJsonObject(response);if(generation!==qaHistoryGeneration||context.generation!==qaHistoryGeneration)return;qaThreadId=threadId;try{sessionStorage.setItem('studybuddy.qa.thread',threadId)}catch(_){}renderHistory(data);await refreshQaHistory()}catch(_){if(generation===qaHistoryGeneration){document.querySelector('#qa-thread-status').textContent='对话加载失败';setQaStatus('问答历史加载失败','error')}}}
async function refreshQaHistory(){const generation=++qaHistoryGeneration;const list=document.querySelector('#qa-history-list');const status=document.querySelector('#qa-history-status');status.textContent='加载中';try{const response=await fetch('/api/qa/threads');const data=await readJsonObject(response);if(generation!==qaHistoryGeneration)return;list.replaceChildren();if(!data.items?.length){status.textContent='暂无问答历史';return}status.textContent=`${data.items.length} 个对话`;data.items.forEach(item=>{const button=document.createElement('button');button.type='button';button.textContent=`${item.title||'未命名对话'} · ${item.message_count} 条消息 · ${item.status==='failed'?'失败':item.status==='empty'?'空对话':'进行中'}`;button.className=item.id===qaThreadId?'active':'';button.setAttribute('aria-current',item.id===qaThreadId?'true':'false');button.onclick=()=>loadQaHistory(item.id);list.append(button)})}catch(_){if(generation===qaHistoryGeneration)status.textContent='对话列表加载失败'}}
function newQaThread(){if(qaInFlight){uiGeneration++;qaInFlight=false}qaHistoryGeneration++;qaThreadId=null;qaLastQuestion='';qaLastError=null;document.querySelector('#qa-question').value='';document.querySelector('#qa-thread-title').textContent='新对话';document.querySelector('#qa-thread-status').textContent='尚未发送问题';document.querySelector('#qa-timeline').replaceChildren(textNode('div','meta qa-empty','新对话尚未有消息'));updateNavContext();document.querySelector('#qa-answer').replaceChildren();document.querySelector('#qa-citations').replaceChildren();document.querySelector('#qa-retry').hidden=true;setQaStatus('已新建对话，请确认材料范围后提问');renderQaScope();refreshQaIndex();document.querySelector('#qa-question').focus()}
async function openCitation(citation,fromNavigation=false){citationNavigationKey=citation.citation_key||null;writeNavigation(false);if(!fromNavigation)showCitationDialog(citation);if(citation.status!=='valid'){setQaStatus(citation.status==='source_deleted'?'引用来源已删除':'引用来源已不可用');return}const returnContext={thread:qaThreadId,scope:qaScopeIds.slice()};const changedMaterial=citation.material_id!==selectedMaterialId;if(changedMaterial){await loadMaterial(citation.material_id,true)}if(selectedMaterialId!==citation.material_id||!selectedMaterial)return;qaThreadId=returnContext.thread;qaScopeIds=returnContext.scope;writeNavigation(true);const start=citation.start_offset,end=citation.end_offset;if(typeof start==='number'&&typeof end==='number'){renderCitationLocation(selectedMaterial.text||'',start,end);if(changedMaterial||fromNavigation)closeCitationDialog();setQaStatus('已定位引用来源')}}
function clearMaterial(){detailGeneration++;uiGeneration++;selectedMaterialId=null;selectedMaterial=null;document.querySelector('#title').textContent='选择材料';document.querySelector('#meta').textContent='';document.querySelector('#warnings').textContent='';document.querySelector('#spans').textContent='';document.querySelector('#content').textContent='';document.querySelector('#rename').disabled=true;document.querySelector('#delete').disabled=true;document.querySelector('#restore').disabled=true;document.querySelector('#purge').disabled=true;document.querySelector('#download-original').disabled=true;document.querySelector('#export-text').disabled=true;clearQa()}
function queryTokens(){return currentQuery.trim().split(/\s+/).filter(Boolean)}
function firstTextMatch(text,tokens){const lowered=text.toLocaleLowerCase();let found=null;for(const token of tokens){const start=lowered.indexOf(token.toLocaleLowerCase());if(start>=0&&(!found||start<found.start))found={start,end:start+token.length,token:text.slice(start,start+token.length)}}return found}
function renderDetailContent(text){const content=document.querySelector('#content');content.replaceChildren();const match=viewMode==='active'&&currentQuery?firstTextMatch(text,queryTokens()):null;if(!match){content.append(document.createTextNode(text));return null}content.append(document.createTextNode(text.slice(0,match.start)));const mark=document.createElement('mark');mark.className='search-highlight';mark.textContent=match.token;content.append(mark,document.createTextNode(text.slice(match.end)));requestAnimationFrame(()=>mark.scrollIntoView({block:'center',inline:'nearest'}));return match}
function searchContext(name,text){if(viewMode!=='active'||!currentQuery)return '';const tokens=queryTokens();const nameMatch=tokens.some(token=>name.toLocaleLowerCase().includes(token.toLocaleLowerCase()));const textMatch=tokens.some(token=>text.toLocaleLowerCase().includes(token.toLocaleLowerCase()));const fields=[];if(nameMatch)fields.push('名称');if(textMatch)fields.push('正文');return fields.length?`搜索命中：${fields.join('、')}`:''}
function qaMessage(code){return ({embedding_provider_not_configured:'Embedding 尚未配置，混合模式已回退到词法检索',embedding_provider_unavailable:'Embedding 服务暂时不可用，混合模式已回退到词法检索',embedding_provider_timeout:'Embedding 服务超时，混合模式已回退到词法检索',provider_invalid_config:'AI Provider 配置不完整，请检查运行配置',provider_not_configured:'AI 服务尚未配置',provider_timeout:'AI 服务响应超时，请稍后重试',provider_connection_failed:'AI 服务连接失败，请检查网络后重试',provider_rate_limited:'AI 服务请求过于频繁，请稍后重试',provider_quota_exceeded:'AI 服务额度不足，请检查 Provider 配置',provider_auth_failed:'AI 服务认证失败，请检查 Provider 配置',provider_forbidden:'AI 服务拒绝了请求，请检查 Provider 配置',provider_unavailable:'AI 服务暂时不可用，请稍后重试',provider_malformed_response:'AI 服务返回了无效响应',provider_schema_mismatch:'AI 服务返回格式不受支持',provider_refusal:'AI 服务拒绝生成回答',provider_output_too_large:'AI 服务回答超过允许大小',retrieval_not_ready:'请先为当前材料建立 AI 索引',retrieval_empty:'当前材料中未找到相关内容',source_deleted:'当前材料不可用',qa_generation_failed:'生成回答失败'})[code]||'问答请求失败'}
function setQaBusy(busy){qaInFlight=busy;const active=viewMode==='active'&&qaScopeIds.length>0;document.querySelector('#qa-question').disabled=busy||!active;document.querySelector('#qa-ask').disabled=busy||!active;document.querySelector('#ai-index').disabled=busy||!selectedMaterialId;document.querySelector('#qa-index').disabled=busy||!qaScopeIds.length}
async function refreshQaIndex(){if(viewMode!=='active'||!qaScopeIds.length){document.querySelector('#qa-question').disabled=true;document.querySelector('#qa-ask').disabled=true;return}const context=currentUi();try{const results=await Promise.all(qaScopeIds.map(id=>fetch(`/api/materials/${encodeURIComponent(id)}/ai-index`).then(async response=>response.ok?readJsonObject(response):{status:'unavailable'})));if(!stillCurrent(context))return;const ready=results.length>0&&results.every(data=>data.status==='ready');const empty=results.some(data=>data.status==='empty');document.querySelector('#qa-question').disabled=!ready;document.querySelector('#qa-ask').disabled=!ready;document.querySelector('#ai-index').disabled=false;document.querySelector('#qa-index').disabled=false;setQaStatus(ready?'可以基于选中材料提问':empty?'选中的材料没有可用于问答的正文':'请先建立 AI 索引（选中材料）')}catch(_){if(stillCurrent(context))setQaStatus('AI 索引状态获取失败','error')}}
function renderCitationLocation(text,start,end){const content=document.querySelector('#content');content.replaceChildren();content.append(document.createTextNode(text.slice(0,start)));const mark=document.createElement('mark');mark.className='citation-highlight';mark.textContent=text.slice(start,end);content.append(mark,document.createTextNode(text.slice(end)));requestAnimationFrame(()=>mark.scrollIntoView({block:'center',inline:'nearest'}))}
async function locateCitation(key,fromNavigation=false){const context=currentUi();try{const r=await fetch('/api/qa/citations/'+encodeURIComponent(key));if(!r.ok)throw Error('citation');const data=await readJsonObject(r);if(!stillCurrent(context))return;data.citation_key=key;await openCitation(data,fromNavigation)}catch(_){if(stillCurrent(context))setQaStatus('引用定位失败','error')}}
function renderQaAnswer(payload){const answer=document.querySelector('#qa-answer'),citations=document.querySelector('#qa-citations');if(payload.retrieval?.fallback){setQaStatus(`回答已生成（已回退：${payload.retrieval.fallback_reason||'词法检索'}）`)}answer.textContent=payload.answer_text;citations.replaceChildren();const timeline=document.querySelector('#qa-timeline');timeline.querySelector('.qa-empty')?.remove();const userRow=textNode('article','qa-message qa-message-user','');userRow.append(textNode('div','qa-message-label','你的问题'));userRow.append(textNode('div','qa-message-user',qaLastQuestion));timeline.append(userRow);const row=textNode('article','qa-message qa-message-assistant','');row.append(textNode('div','qa-message-label','AI 回答'));row.append(textNode('div','qa-message-assistant',payload.answer_text));const citeRow=textNode('div','qa-citations','');(payload.citations||[]).forEach(citation=>{const button=document.createElement('button');button.type='button';button.textContent=`引用 ${citation.position}`;button.onclick=()=>locateCitation(citation.citation_key);citeRow.append(button)});row.append(citeRow);timeline.append(row);timeline.